//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_sys_serverinfo
    {
        public string ServerInfoId { get; set; }
        public string IPAddress { get; set; }
        public Nullable<float> CPUValue { get; set; }
        public Nullable<float> MemoryValue { get; set; }
        public Nullable<float> DiskValue { get; set; }
        public Nullable<System.DateTime> InputTime { get; set; }
        public string SystemId { get; set; }
    }
}
