//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_sys_function
    {
        public string functionid { get; set; }
        public string functioncode { get; set; }
        public string functionname { get; set; }
        public int status { get; set; }
        public int systemcategory { get; set; }
        public string parentid { get; set; }
        public int ismenu { get; set; }
        public string menucode { get; set; }
        public string menuname { get; set; }
        public string menuicon { get; set; }
        public string menuurl { get; set; }
        public int isexpand { get; set; }
        public string helpertitle { get; set; }
        public string helperurl { get; set; }
        public int sort { get; set; }
        public string remark { get; set; }
        public int ispublic { get; set; }
        public string createuserid { get; set; }
        public string createusername { get; set; }
        public Nullable<System.DateTime> createdatetime { get; set; }
        public string edituserid { get; set; }
        public string editusername { get; set; }
        public Nullable<System.DateTime> editdatetime { get; set; }
        public string ownerid { get; set; }
        public string ownername { get; set; }
        public int isdeleted { get; set; }
    }
}
