//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_sys_userrole
    {
        public string userroleid { get; set; }
        public string userid { get; set; }
        public string roleid { get; set; }
        public string createuserid { get; set; }
        public string createusername { get; set; }
        public Nullable<System.DateTime> createdatetime { get; set; }
        public string edituserid { get; set; }
        public string editusername { get; set; }
        public Nullable<System.DateTime> editdatetime { get; set; }
        public string ownerid { get; set; }
        public string ownername { get; set; }
        public int isdeleted { get; set; }
    }
}
