//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_sys_metadata
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DataType { get; set; }
        public Nullable<int> DataSourceType { get; set; }
        public string DataSource { get; set; }
        public string DataSourceColumn { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string EditUserId { get; set; }
        public string EditUserName { get; set; }
        public Nullable<System.DateTime> EditDateTime { get; set; }
        public string OwnerId { get; set; }
        public string OwnerName { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
