//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_sys_userregrecord
    {
        public string UserRegRecordId { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string LoginName { get; set; }
        public string MobilePhone { get; set; }
        public string Address { get; set; }
        public string UserSource { get; set; }
        public Nullable<System.DateTime> InputTime { get; set; }
        public string SystemId { get; set; }
    }
}
