//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_sys_systeminfo
    {
        public string SystemId { get; set; }
        public string SystemName { get; set; }
        public string CreateLoginName { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string ModifyLoginName { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
        public Nullable<int> IsValid { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
