//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_sys_rolefunctionorg
    {
        public string rolefunctionorgid { get; set; }
        public string rolefunctionid { get; set; }
        public string orgtype { get; set; }
        public string orgid { get; set; }
        public string orgname { get; set; }
        public string createuser { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string updateuser { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
    }
}
