//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_sup_doctor
    {
        public string doctorid { get; set; }
        public string docname { get; set; }
        public Nullable<int> docsex { get; set; }
        public Nullable<System.DateTime> brithday { get; set; }
        public string idnumber { get; set; }
        public string docprovince { get; set; }
        public string doccity { get; set; }
        public string dochospital { get; set; }
        public string docdepartment { get; set; }
        public string doctitle { get; set; }
        public string docmajor { get; set; }
        public string docdisease { get; set; }
        public string diseasecode { get; set; }
        public string docdescrip { get; set; }
        public string checkstatus { get; set; }
        public string createuserid { get; set; }
        public string createusername { get; set; }
        public Nullable<System.DateTime> createdatetime { get; set; }
        public string edituserid { get; set; }
        public string editusername { get; set; }
        public Nullable<System.DateTime> editdatetime { get; set; }
        public string ownerid { get; set; }
        public string ownername { get; set; }
        public int isdeleted { get; set; }
        public string userid { get; set; }
        public string onlinestatus { get; set; }
        public string checkremark { get; set; }
        public string banktype { get; set; }
        public string bankname { get; set; }
        public string bankcardint { get; set; }
        public string ownerpostid { get; set; }
        public string ownerdepartmentid { get; set; }
        public string ownercompanyid { get; set; }
        public string commoncontact { get; set; }
    }
}
