//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_area
    {
        public string areaname { get; set; }
        public int level { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public string updateby { get; set; }
        public Nullable<int> status { get; set; }
        public string areaid { get; set; }
        public string parentid { get; set; }
    }
}
