//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_cnr_user
    {
        public string userid { get; set; }
        public string personid { get; set; }
        public string localism { get; set; }
        public string area { get; set; }
        public string disease { get; set; }
        public Nullable<System.DateTime> creattime { get; set; }
        public string creatby { get; set; }
        public Nullable<System.DateTime> modifytime { get; set; }
        public string modifyby { get; set; }
        public string idcard { get; set; }
        public string username { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string doctorid { get; set; }
        public string ismarryed { get; set; }
        public string ispregnant { get; set; }
        public string addressdetail { get; set; }
        public string diseasecode { get; set; }
        public string diseasetnm { get; set; }
        public string ctmsstep { get; set; }
        public string allergyhis { get; set; }
        public string personhistory { get; set; }
        public string obstetricalhistory { get; set; }
        public string menstrualhistory { get; set; }
        public string currentstep { get; set; }
        public Nullable<int> userheight { get; set; }
        public Nullable<int> userweight { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public string town { get; set; }
        public string ownerid { get; set; }
        public string ownerpostid { get; set; }
        public string ownerdepartmentid { get; set; }
        public string ownercompanyid { get; set; }
    }
}
