//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_dictionary
    {
        public string dictionaryid { get; set; }
        public string fatherid { get; set; }
        public string dictioncategory { get; set; }
        public string dictionaryname { get; set; }
        public string dictionaryvalue { get; set; }
        public string createuser { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string updateuser { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public string dictioncategoryname { get; set; }
        public string remark { get; set; }
        public string systemname { get; set; }
        public string systemcode { get; set; }
        public Nullable<int> ordernumber { get; set; }
        public string systemneed { get; set; }
        public Nullable<int> isdeleted { get; set; }
    }
}
