//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tmpmEntities2 : DbContext
    {
        public tmpmEntities2()
            : base("name=tmpmEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ctms_hr_company> ctms_hr_company { get; set; }
        public DbSet<ctms_hr_department> ctms_hr_department { get; set; }
        public DbSet<ctms_hr_post> ctms_hr_post { get; set; }
        public DbSet<ctms_hr_userpost> ctms_hr_userpost { get; set; }
        public DbSet<ctms_myproduct> ctms_myproduct { get; set; }
        public DbSet<ctms_pm_dotask> ctms_pm_dotask { get; set; }
        public DbSet<ctms_pm_itemconfirm> ctms_pm_itemconfirm { get; set; }
        public DbSet<ctms_pm_itemreport> ctms_pm_itemreport { get; set; }
        public DbSet<ctms_pm_project> ctms_pm_project { get; set; }
        public DbSet<ctms_pm_task> ctms_pm_task { get; set; }
        public DbSet<ctms_sup_doctor> ctms_sup_doctor { get; set; }
        public DbSet<ctms_sup_doctorgroup> ctms_sup_doctorgroup { get; set; }
        public DbSet<ctms_sup_doctorgroupdetail> ctms_sup_doctorgroupdetail { get; set; }
        public DbSet<ctms_sup_doctorpatient> ctms_sup_doctorpatient { get; set; }
        public DbSet<ctms_sys_entitymenu> ctms_sys_entitymenu { get; set; }
        public DbSet<ctms_sys_errorcount> ctms_sys_errorcount { get; set; }
        public DbSet<ctms_sys_function> ctms_sys_function { get; set; }
        public DbSet<ctms_sys_metadata> ctms_sys_metadata { get; set; }
        public DbSet<ctms_sys_metadataparam> ctms_sys_metadataparam { get; set; }
        public DbSet<ctms_sys_modelsetting> ctms_sys_modelsetting { get; set; }
        public DbSet<ctms_sys_permission> ctms_sys_permission { get; set; }
        public DbSet<ctms_sys_role> ctms_sys_role { get; set; }
        public DbSet<ctms_sys_rolefunction> ctms_sys_rolefunction { get; set; }
        public DbSet<ctms_sys_rolefunctionorg> ctms_sys_rolefunctionorg { get; set; }
        public DbSet<ctms_sys_serveralarm> ctms_sys_serveralarm { get; set; }
        public DbSet<ctms_sys_serverinfo> ctms_sys_serverinfo { get; set; }
        public DbSet<ctms_sys_servermonitor> ctms_sys_servermonitor { get; set; }
        public DbSet<ctms_sys_sysmonitor> ctms_sys_sysmonitor { get; set; }
        public DbSet<ctms_sys_systeminfo> ctms_sys_systeminfo { get; set; }
        public DbSet<ctms_sys_userinfo> ctms_sys_userinfo { get; set; }
        public DbSet<ctms_sys_userregrecord> ctms_sys_userregrecord { get; set; }
        public DbSet<ctms_sys_userrole> ctms_sys_userrole { get; set; }
        public DbSet<ctms_tk_timedtask> ctms_tk_timedtask { get; set; }
        public DbSet<ctms_tk_timedtaskdefine> ctms_tk_timedtaskdefine { get; set; }
        public DbSet<ctms_tk_timedtaskhis> ctms_tk_timedtaskhis { get; set; }
        public DbSet<hr_area> hr_area { get; set; }
        public DbSet<hr_cnr_user> hr_cnr_user { get; set; }
        public DbSet<hr_dictionary> hr_dictionary { get; set; }
    }
}
