//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.TIMER.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTMS_MYPRODUCT> CTMS_MYPRODUCT { get; set; }
        public virtual DbSet<CTMS_OD_ORDERS> CTMS_OD_ORDERS { get; set; }
        public virtual DbSet<CTMS_SUP_REQUESTRECORD> CTMS_SUP_REQUESTRECORD { get; set; }
        public virtual DbSet<CTMS_SYS_USERINFO> CTMS_SYS_USERINFO { get; set; }
        public virtual DbSet<CTMS_TK_TIMEDTASK> CTMS_TK_TIMEDTASK { get; set; }
        public virtual DbSet<CTMS_TK_TIMEDTASKDEFINE> CTMS_TK_TIMEDTASKDEFINE { get; set; }
        public virtual DbSet<CTMS_USEREVENT> CTMS_USEREVENT { get; set; }
    }
}
