//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.TIMER.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMS_SYS_USERINFO
    {
        public string USERID { get; set; }
        public string LOGINNAME { get; set; }
        public string LOGINPWD { get; set; }
        public string MOBILEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string CREATEUSERID { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATETIME { get; set; }
        public string OWNERID { get; set; }
        public bool ISDELETED { get; set; }
        public string CREATEUSERNAME { get; set; }
        public string EDITUSERNAME { get; set; }
        public string OWNERNAME { get; set; }
        public Nullable<decimal> USERTYPE { get; set; }
        public int USERSTATUS { get; set; }
        public decimal ACCOUNT { get; set; }
        public string MEMBERID { get; set; }
        public Nullable<System.DateTime> MEMBERSTARTDATE { get; set; }
        public Nullable<System.DateTime> MEMBERENDDATE { get; set; }
        public string USERNAME { get; set; }
        public string ICONPATH { get; set; }
        public string OWNERPOSTID { get; set; }
        public string OWNERDEPARTMENTID { get; set; }
        public string OWNERCOMPANYID { get; set; }
    }
}
