//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.CTMS.TIMER.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMS_MYPRODUCT
    {
        public string MYPRODUCTID { get; set; }
        public string USERID { get; set; }
        public string LOGINNAME { get; set; }
        public string ORDERID { get; set; }
        public string PRODUCTCODE { get; set; }
        public string PRODUCTID { get; set; }
        public string PRODUCTNAME { get; set; }
        public int PRODUCTNUM { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public bool ISUSED { get; set; }
        public Nullable<System.DateTime> USEDDATE { get; set; }
        public string CREATEUSERID { get; set; }
        public string CREATEUSERNAME { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string EDITUSERID { get; set; }
        public string EDITUSERNAME { get; set; }
        public Nullable<System.DateTime> EDITDATETIME { get; set; }
        public string OWNERID { get; set; }
        public string OWNERNAME { get; set; }
        public bool ISDELETED { get; set; }
    }
}
